---
- name: Test connectivity to MikroTik devices
  hosts: mikrotik
  gather_facts: false
  connection: local

  tasks:
    - name: Run command over SSH manually
      ansible.builtin.command: >
        ssh -o BatchMode=yes -o StrictHostKeyChecking=no 
        -o KexAlgorithms=+diffie-hellman-group1-sha1 
        -o HostKeyAlgorithms=+ssh-rsa
        {{ ansible_user }}@{{ ansible_host }} 
        "/system identity print"
      register: command_output
      changed_when: false

    - name: Display command output
      ansible.builtin.debug:
        var: command_output.stdout
