# tasks file for update_debian_systems

- name: Update package list and install upgrades (Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
  register: apt_update_result

- name: Install updates (RedHat/CentOS)
  ansible.builtin.dnf:
    name: '*'
    state: latest
    autoremove: yes
  when: ansible_os_family == "RedHat"
  register: dnf_update_result

- name: Check if reboot is required (Debian/Ubuntu)
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_os_family == "Debian"

- name: Show reboot required information
  ansible.builtin.debug:
    msg: "WARNING: A server reboot is required to complete the update process!"
  when: reboot_required_file.stat.exists is defined and reboot_required_file.stat.exists

- name: Show successful completion message
  ansible.builtin.debug:
    msg: "System has been successfully updated."
  when: apt_update_result.changed